/**
 * Publisher interface (ADR 0002) — the single seam between our domain logic and
 * the platform APIs (Facebook, Instagram, TikTok).
 *
 * All publishing goes through this abstraction with one implementation per
 * platform transport, so a platform can be swapped (to an aggregator, or the
 * BYO-token path of ADR 0008) without touching domain code. In tests the real
 * transports are replaced by {@link FakePublisher}, which records what *would*
 * be sent and can be scripted to succeed or fail per platform — no real
 * Meta/TikTok calls ever occur in the behavioral suite.
 *
 * The seam covers a Connected Account's whole lifecycle, not just publishing:
 * authorizing (OAuth), discovering what the credential may publish to
 * (`pages_show_list`), refreshing before expiry, and finally publishing. They
 * are one interface because they are one relationship with one platform API —
 * and because the fallbacks ADR 0002 exists for (an aggregator, or ADR 0008's
 * BYO token) replace all of them together or none of them.
 */

export type Platform = "facebook" | "instagram" | "tiktok";

export const PLATFORMS: readonly Platform[] = ["facebook", "instagram", "tiktok"];

/** What we ask a platform transport to publish for a single Target. */
export interface PublishRequest {
  platform: Platform;
  /** The Post's text/caption. */
  text: string;
  /** Public HTTPS URL of the attached Media, if any. */
  mediaUrl?: string;
}

/** The outcome of a single publish attempt for one Target. */
export type PublishResult =
  | {
      ok: true;
      /** The platform's durable post/media ID, persisted per Target on success. */
      externalId: string;
      /** Link to the live post on the platform, if the transport returns one. */
      permalink?: string;
    }
  | {
      ok: false;
      /** Human-readable reason, surfaced on the Target for a manual retry. */
      error: string;
    };

/**
 * A platform credential in its usable, decrypted form. Always encrypted at rest
 * (ADR 0006) — this shape only ever exists in memory.
 *
 * ADR 0008: the slot accepts either an OAuth-obtained token or a manually-pasted
 * long-lived Page token, and both are consumed identically from here. A
 * manually-pasted token cannot auto-refresh, which is what `refreshable` records.
 */
export interface PlatformCredential {
  accessToken: string;
  /** When the token stops working, if the platform tells us. */
  expiresAt?: Date;
  /**
   * Whether {@link Publisher.refreshCredential} can extend this token. False for
   * a hand-pasted token (ADR 0008), which must be regenerated by a human.
   */
  refreshable: boolean;
  /**
   * The platform's id for the *authorizing person* (e.g. the Meta user id).
   * Not the Page id — this is what a deauthorization callback names.
   */
  platformUserId?: string;
  /**
   * The token this one was derived from, where the platform works that way.
   *
   * Meta is the reason this exists: we publish with a *Page* token, but Meta
   * will only ever extend the *user* token it was derived from — so refreshing
   * means re-extending the parent and re-deriving the Page token from it. Kept
   * on the credential because it is sealed and stored with it (ADR 0006), and is
   * useless to anything but a refresh.
   */
  parentToken?: string;
}

/** Where to send a User to authorize us against a platform. */
export interface AuthorizeRequest {
  platform: Platform;
  /** Opaque anti-forgery value round-tripped through the platform. */
  state: string;
  /** The callback URL the platform returns the User to. */
  redirectUri: string;
}

/** An OAuth callback's authorization code, to be traded for a credential. */
export interface ExchangeRequest {
  platform: Platform;
  code: string;
  redirectUri: string;
}

/** A credential to extend, and the destination it publishes to. */
export interface RefreshRequest {
  platform: Platform;
  credential: PlatformCredential;
  /**
   * The Connected Account's destination id (the Page id). Needed because a
   * transport may not be able to extend the credential in place: Meta re-derives
   * the Page token from the refreshed user token, and must be told which Page.
   */
  externalId: string;
}

/**
 * A Facebook Page the authorizing person manages, as returned by
 * `pages_show_list`. Per ADR 0005 this list *is* the enforcement: it contains
 * only Pages, never personal profiles, so an empty list is a genuine dead-end
 * rather than something to work around.
 */
export interface FacebookPage {
  /** The Page id. Publishing always targets this, never a personal profile id. */
  id: string;
  name: string;
  /** The Page access token — what we actually publish with, not the user token. */
  credential: PlatformCredential;
}

/**
 * A platform's refusal, as opposed to a bug in our code. Routes map this to a
 * 502 rather than a 500: the request was fine, the platform said no.
 */
export class PublisherError extends Error {
  constructor(
    readonly platform: Platform,
    message: string,
  ) {
    super(message);
    this.name = "PublisherError";
  }
}

export interface Publisher {
  publish(request: PublishRequest): Promise<PublishResult>;

  /** The URL to send the User to, to begin authorizing (OAuth start). */
  authorizeUrl(request: AuthorizeRequest): string;

  /**
   * Trade an OAuth callback code for a credential.
   *
   * @throws {PublisherError} if the platform rejects the code.
   */
  exchangeCode(request: ExchangeRequest): Promise<PlatformCredential>;

  /**
   * The Facebook Pages this credential manages (`pages_show_list`, ADR 0005).
   * An empty array means the person manages no Page — a dead-end, not an error.
   *
   * @throws {PublisherError} if the platform rejects the credential.
   */
  listFacebookPages(credential: PlatformCredential): Promise<FacebookPage[]>;

  /**
   * Extend a credential nearing expiry, for the token-refresh job.
   *
   * @throws {PublisherError} if the platform will not extend it — the caller
   * marks the Connected Account `token_expired` so the User can reconnect.
   */
  refreshCredential(request: RefreshRequest): Promise<PlatformCredential>;
}
